### ISSUE TITLE
UNKNOWN - Error: Unknown error

### ISSUE THREAD

**Issue by sarojamarraj** [PatrickNByrne/check_freenas#1]
I followed README and ended up with below output when ran the CMD manually

UNKNOWN - Error: Unknown error

**Comment by PatrickNByrne** [comment]
Please check your connection to the server, and verify that you're using the root user/password.

**Comment by PatrickNByrne** [comment]
I've also released a new version of the plugin that allows for more verbose output. If you still receive this error, please use the `-v` flag to enable verbose output.
