### ISSUE TITLE
[Suggestion] Output Alerts in a nagios friendly way with the correct return code

### ISSUE THREAD

**Issue by ghost** [PatrickNByrne/check_freenas#2]
Right now a check for system alerts return something like the following (when using a warning for example):
`{u'meta': {u'previous': None, u'total_count': 1, u'offset': 0, u'limit': 20, u'next': None}, u'objects': [{u'timestamp': 1547071515, u'message': u'New feature flags are available for volume Pool. Refer to the "Upgrading a ZFS Pool" subsection in the User Guide "Installing and Upgrading" chapter and "Upgrading" section for more instructions.', u'id': u'A;VolumeVersion;["New feature flags are available for volume %s. Refer to the \\"Upgrading a ZFS Pool\\" subsection in the User Guide \\"Installing and Upgrading\\" chapter and \\"Upgrading\\" section for more instructions.", "Pool"]', u'dismissed': False, u'level': u'WARNING'}]}`

It would be interesting to get it in a Nagios friendly way in this style:
`WARNING - New feature flags are available for volume Pool. Refer to the "Upgrading a ZFS Pool" subsection in the User Guide "Installing and Upgrading" chapter and "Upgrading" section for more instructions.`

by reading the _message_ and _level_ section of the message.

**Comment by PatrickNByrne** [comment]
Great suggestion! I just uploaded a new version. Please let me know if that works for you. Thanks!

**Comment by ghost** [comment]
Work perfectly ! Thanks for your work !
