### ISSUE TITLE
CRITICAL - Disk stripe is offline 

### ISSUE THREAD

**Issue by emmcdonald** [PatrickNByrne/check_freenas#4]
There looks to be a bug in the checking of disks on certain FreeNAS systems (11.2-STABLE and 11.3-RELEASE) with this script. The following is reported even when all disks are nominal.

**CRITICAL - Disk stripe is offline**
 
This is my simple patch to lines 98 & 99 to filter out disks/lines marked as "AVAIL" as this is erroneous.

```
                        if (disk['status'] != 'ONLINE' and disk['status'] != 'AVAIL'):
                            return (2, "Disk " + disk['name'] + " is " + disk['status'], None)
```

After the patch,

**OK - All disks are online**

**Comment by PatrickNByrne** [comment]
Ahh, interesting. Thank you for reporting this! I've updated the code and released version 1.3.3 that contains your suggested fix. Please give that a shot when you get a moment and confirm that it works for you before I close this out. 

Thanks!
